module ApplicationHelper
  def campaign_report_open_list_responses
    [
      "type",
      "userid",
      "segmentid",
      "bounceid",
      "realcid",
      "sendid",
      "threadid",
      "seriesid",
      "formid",
      "basetemplateid",
      "basemessageid",
      "addressid",
      "source",
      "name",
      "cdate",
      "mdate",
      "sdate",
      "ldate",
      "send_amt",
      "total_amt",
      "opens",
      "uniqueopens",
      "linkclicks",
      "uniquelinkclicks",
      "subscriberclicks",
      "forwards",
      "uniqueforwards",
      "hardbounces",
      "softbounces",
      "unsubscribes",
      "unsubreasons",
      "updates",
      "socialshares",
      "replies",
      "uniquereplies",
      "status",
      "public",
      "mail_transfer",
      "mail_send",
      "mail_cleanup",
      "mailer_log_file",
      "tracklinks",
      "tracklinksanalytics",
      "trackreads",
      "trackreadsanalytics",
      "analytics_campaign_name",
      "tweet",
      "facebook",
      "survey",
      "embed_images",
      "htmlunsub",
      "textunsub",
      "htmlunsubdata",
      "textunsubdata",
      "recurring",
      "willrecur",
      "split_type",
      "split_content",
      "split_offset",
      "split_offset_type",
      "split_winner_messageid",
      "split_winner_awaiting",
      "responder_offset",
      "responder_type",
      "responder_existing",
      "reminder_field",
      "reminder_format",
      "reminder_type",
      "reminder_offset",
      "reminder_offset_type",
      "reminder_offset_sign",
      "reminder_last_cron_run",
      "activerss_interval",
      "activerss_url",
      "activerss_items",
      "ip4",
      "laststep",
      "managetext",
      "schedule",
      "scheduleddate",
      "waitpreview",
      "replysys"
    ]
  end

  def render_csv(csv)
    csv_value = ""

    csv.each do |item|
      csv_value += "#{item.join(',')}"
    end

    csv_value.html_safe
  end
end
